name: bottom_bar_page_transition
description: To display animation between pages while using bottom bar navigation.
version: 1.0.3
homepage: https://github.com/mdalameen/bottom_bar_page_transition

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: